### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'end'

### ISSUE THREAD

**Issue by The-SamminAter** [MichalMotylinski/DiscordExtractor#1]
Hello,
I am trying to use DiscFor to recover messages from my Discord cache, however, it fails every time. I am using Python 3.10.5 on Linux 5.18.10-1. Here is the error/output:

```
$ python discfor.py
===================================================
DISCFOR MAIN MENU
===================================================
1. Extraction from current file system
2. Select folder for extraction
3. Quit

Enter choice: 1

Please provide output path
/home/thethesamminaterminater/Desktop/discordExtracted  

Searching system...

Discord folder found under:
/home/thesamminater/.config/discord

Type [y/yes] to accept the result or [n/no] to continue search:
y

Do you want to create data backup? (y/yes or n/no)
y

Creating data backup...
Backup created successfully in:  3.51 s

Beginning data extraction...
Traceback (most recent call last):
  File "/home/thesamminater/Desktop/DiscFor-Discord-Artefact-Extraction-Tool/discfor.py", line 211, in <module>
    main_menu()
  File "/home/thesamminater/Desktop/DiscFor-Discord-Artefact-Extraction-Tool/discfor.py", line 76, in main_menu
    main_menu()
  File "/home/thesamminater/Desktop/DiscFor-Discord-Artefact-Extraction-Tool/discfor.py", line 48, in main_menu
    recovery(discord_path, output_path)
  File "/home/thesamminater/Desktop/DiscFor-Discord-Artefact-Extraction-Tool/discfor.py", line 182, in recovery
    cache_data_list, all_entries, recovered, empty_entries, reconstructed = read_simple_cache(discord_path, output_dir)
  File "/home/thesamminater/Desktop/DiscFor-Discord-Artefact-Extraction-Tool/simplecache.py", line 37, in read_simple_cache
    cache_file.seek(eof1.end() + 7, SEEK_SET)
AttributeError: 'NoneType' object has no attribute 'end'
```

Any help would be greatly appreciated, as Discord disabled my account for reasons unknown to me and isn't responding to my help requests/appeals.

**Comment by The-SamminAter** [comment]
To be clear, `~/Desktop/discordExtracted/Dump_{yyyymmddhhmmss}/Extracted/Chat_logs/` has a whole bunch of seemingly unreadable .br files, and `~/Desktop/discordExtracted/Dump_{yyyymmddhhmmss}/Reports/Chat_logs/` is empty.

**Comment by MichalMotylinski** [comment]
Hi Sam,
I am on holiday until Wednesday but once I am back I will check that error
for you.
Probably Discord updated how they store things internally and program gets
stuck trying to read that value.
Until then please keep the backup of your Discord cache so it won't get
overwritten.

Kind regards,
Michal

**Comment by The-SamminAter** [comment]
No worries, take as much time as you need, and thank you so much for responding.

I took a backup before launching the app, and have no account to open Discord to until/unless they decide to reverse their decision.

**Comment by MichalMotylinski** [comment]
Hi Sam,
It seems like the function cannot find the end of the cache file record
which is a bunch of bytes.
I have updated the program so it should not throw an error anymore, however
the file in question will not be read.
I also added support for brotli files. Initially it wasn't supported
because only handful of files were in this format but it seems they changed
it.
As a result you will have to download the brotli module to your python
environment using the following: "pip install brotli".

Please try a new version and let me know if it works.

Kind regards,
Michal

**Comment by The-SamminAter** [comment]
Hey, sorry for taking so long to get back to you. I tried re-running it, and it crashed again. Here's the log:
```
$ python discfor.py
===================================================
DISCFOR MAIN MENU
===================================================
1. Extraction from current file system
2. Select folder for extraction
3. Quit

Enter choice: 1

Please provide output path
~/Desktop/discordExtracted

Searching system...

Discord folder found under:
~/.config/discord

Type [y/yes] to accept the result or [n/no] to continue search:
y

Do you want to create data backup? (y/yes or n/no)
y

Creating data backup...
Backup created successfully in:  3.58 s

Beginning data extraction...
Traceback (most recent call last):
  File "~/Desktop/DiscFor-Discord-Artefact-Extraction-Tool/discfor.py", line 211, in <module>
    main_menu()
  File "~/Desktop/DiscFor-Discord-Artefact-Extraction-Tool/discfor.py", line 48, in main_menu
    recovery(discord_path, output_path)
  File "~/Desktop/DiscFor-Discord-Artefact-Extraction-Tool/discfor.py", line 182, in recovery
    cache_data_list, all_entries, recovered, empty_entries, reconstructed = read_simple_cache(discord_path, output_dir)
  File "~/Desktop/DiscFor-Discord-Artefact-Extraction-Tool/simplecache.py", line 70, in read_simple_cache
    read_http_response(str(response_data), cache_entry)
  File "~/Desktop/DiscFor-Discord-Artefact-Extraction-Tool/common.py", line 206, in read_http_response
    cache_entry.last_modified_time = time_convert(cache_entry.last_modified_data)
  File "~/Desktop/DiscFor-Discord-Artefact-Extraction-Tool/common.py", line 260, in time_convert
    date = old_time[1] + "/" + month_convert(old_time[2]) + "/" + old_time[3]
  File "~/Desktop/DiscFor-Discord-Artefact-Extraction-Tool/common.py", line 248, in month_convert
    month_num = str("{:02d}".format(months.index(month) + 1))
ValueError: '2020' is not in list
```

**Comment by MichalMotylinski** [comment]
Hi Sam,
Very sorry for getting back to you so late I was pretty busy in the last 2
weeks and had no time to look at the code.
This error should be fixed now. You can download new code or use the
attached files.

Kind regards,
Michal

**Comment by The-SamminAter** [comment]
No worries, in the past two weeks my account got restored, so I now have access to all of my data once again. Thanks for fixing this though!
